config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  #------------------帐号相关-----------------#
  # 注册页面
  match '/signup', to: 'user_accounts#signup', via: 'get'
  # 登录页面
  match '/signin', to: 'user_accounts#signin', via: 'get'
  # 注销页面
  match '/signout', to: 'sessions#destroy', via: 'get'
  # 密码找回页面，输入邮箱和验证码
  match '/requestresetpassword', to: 'user_accounts#requestresetpassword', via: 'get'
  # 账户激活页面
  match '/active', to:'user_accounts#active', via: 'get'
  # 修改密码页面
  match '/resetpassword', to:'user_accounts#resetpassword', via: 'get'
  # 找回密码邮件已发送
  match '/pleasecheckemail', to: 'user_accounts#pleasecheckemail', via: 'get'
  # 返回首页
  match '/backtoroot', to:'static_pages#backtoroot', via:'post'
  #密码找回已重设成功
  match '/resetpasswordsuccessful', to:'user_accounts#resetpasswordsuccessful', via:'get'


  # 提交注册数据
  match '/tosignup', to: 'user_accounts#tosignup', via: 'post'
  # 提交登录数据
  match '/tosignin',  to: 'sessions#tosignin', via: 'post'
  # 提交请求找回密码数据，验证码，邮箱，然后会发送邮件
  match '/torequestresetpassword', to: 'user_accounts#torequestresetpassword', via: 'post'
  # 通过找回密码连接，打开密码重设页面，提交的数据
  match '/toresetpassword', to: 'user_accounts#toresetpassword', via:'post'
  # 找回密码中邮件已发送，点了 重新发送 按钮，重新发送邮件
  match '/toresendemail', to: 'user_accounts#toresendemail', via: 'get'
  #-----------------------------------------------#


  #----------------- 个人资料相关 ----------------#
  # 访问个人资料页
  match '/people/:id', to: 'peoples#show', via: 'get'
  # 更新头像信息
  match '/people/update/head_icon', to: 'peoples#update_head_icon', via:'post'
  # 更新基础资料
  match '/people/update/basic_info', to: 'peoples#update_basic_info', via:'post'
  # 更新近况
  match '/people/update/life_memory', to: 'peoples#update_life_memory', via:'post'
  # 更新参与过的项目
  match '/people/update/person_joined_project', to: 'peoples#update_person_joined_project', via:'post'
  # 更新最近发表过的项目评论
  match '/people/update/project_comment', to: 'peoples#update_project_comment', via:'post'
  # 更新教育信息
  match '/people/update/education', to: 'peoples#update_education', via:'post'
  # 更新技能
  match '/people/update/ability', to: 'peoples#update_ability', via:'post'
  # 更新工作经历
  match '/people/update/work_experience', to: 'peoples#update_work_experience', via:'post'
  #-----------------------------------------------#



  match '/people/update/ajaxtest', to: 'peoples#ajaxtest', via:'get'



end

app/views/layouts/_header.html.erb
<header>
    <div class="co-navbar">
        <div class="co-navbar-item", id="logo">
            <%= link_to "Comet",'#' %>
        </div>

        <div class="co-navbar-item co-navbar-center">
            <ul>
                <li><%= link_to "发现",'#' %></li>
                <li><%= link_to "寻找项目",'#' %></li>
                <li><%= link_to "组队",'#' %></li>
                <li id="co-navbar-start-btn"><%= link_to "开始", '#' %></li>
            </ul>

        </div>

        <div class="co-navbar-item co-navbar-right">
            <ul>
                <% if signed_in? %>
                    <li><%= link_to "注销",signout_path %></li>
                <% else %>
                    <li><%= link_to "登录",signin_path %></li>
                    <li><%= link_to "注册",signup_path %></li>
                <% end %>

            </ul>
        </div>
    </div>
</header>

<!--
<%= render 'layouts/signinup' %>
-->

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9] >
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js" ></script>

<![endif]-->

app/views/layouts/_signinup.html.erb
<h1>This is Sign In And Sign Up</h1>


<div id="signinup_wrapper">
    <div id="signin_wrapper">
        <p class="signinup_title">登录</p>
        <div id="signin">
        <%= form_for(:user_account, :url=>"/login") do |f| %>
            <%= f.email_field :email, :placeholder=>"邮箱地址" %>
            <%= f.password_field :password, :placeholder=>"密码" %>
            <div id="remember_forgot_field">
                <div id="remember_me">
                    <%= f.check_box :remember_signin %>
                    <%= f.label :remember_signin, "记住我" %>
                </div>
                <div id="forgot_password">
                    <%= link_to "忘记密码?" ,'#' %>
                </div>
            </div>
            <div class="signinup_submit_button"><%= f.submit "登录" ,class:"signinup_btn" %></div>
        <% end %>
        </div>
    </div>

    <div id="signup_wrapper">
        <p class="signinup_title">注册</p>
        <div id="signup">
            <%= form_for(:user_account, :url=>"/create") do |f| %>
                <%= f.email_field :email, :placeholder=>"邮箱地址" %>
                <%= f.password_field :password, :placeholder=>"密码" %>
                <div class="signinup_submit_button"><%= f.submit "注册" ,class:"signinup_btn" %></div>
            <% end %>
        </div>

    </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= stylesheet_link_tag 'global' %>

    <%= yield :head %>
</head>
<body>



    <%= yield %>
<!--
    <% flash.each do |key,value| %>
        <div>
            <%= value %>
        </div>
    <% end %>

    <%= render 'layouts/footer' %>

    <%= debug(params) if Rails.env.development? %>
-->

</body>
</html>